### ISSUE TITLE
im2col_gpu_1

### ISSUE THREAD

**Issue by lcaikk1314** [mapleam/drop-blocks#1]
good job. but can you share the definition of "im2col_gpu_1"?

**Comment by Z7zuqer** [comment]
Normal im2col_gpu padding matrix with zero, im2col_gpu_1 padding matrix with one in order to deal with boundries

Besides, later i found some mistakes in my implemention, the convolution should be depth-wise convolution. I will fix it later

**Comment by lcaikk1314** [comment]
3q
